before_script:
    - angr-test sync hard

### local
lint:
    script: "angr-test lint"
    tags: [angr]

### first level
simuvex:
    script: "angr-test simuvex"
    tags: [angr]

angr:
    script: "angr-test angr"
    tags: [angr]

fidget:
    script: "angr-test fidget"
    tags: [angr]

angrop:
    script: "angr-test angrop"
    tags: [angr]

docs:
    script: "angr-test docs"
    tags: [angr]

### other levels
cle:
    script: "angr-test cle"
    tags: [angr]

driller:
    script: "angr-test driller"
    tags: [angr]

tracer:
    script: "angr-test tracer"
    tags: [angr]

topsecret:
    script: "angr-test top-secret"
    tags: [angr]

rex:
    script: "angr-test rex"
    tags: [angr]

pwnrex:
    script: "angr-test pwnrex"
    tags: [angr]
