before_script:
    - angr-test sync hard

# pyvex has no local tests
#pyvex:
#    script: "angr-test pyvex"
#    tags:
#        - "angr"
#    except:
#        - "master"

simuvex:
    script: "angr-test simuvex"
    tags:
        - "angr"
    except:
        - "master"

angr:
    script: "angr-test angr"
    tags:
        - "angr"
    except:
        - "master"

fidget:
    script: "angr-test fidget"
    tags:
        - "angr"
    except:
        - "master"

pyvex_lint:
    script: "angr-test lint"
    tags:
        - "angr"
    except:
        - "master"
