#include <Python.h>
#include <libvex.h>
#include <stdio.h>
#include <string.h>
#include "pymare.h"
#include "pyvex_logging.h"
#include "pyvex_enums.h"

PYMARE_ENUM_CONVERSION(VexArch)
PYMARE_ENUM_CONVERSION(IRExprTag)
PYMARE_ENUM_CONVERSION(IRStmtTag)
PYMARE_ENUM_CONVERSION(IREndness)
PYMARE_ENUM_CONVERSION(IRMBusEvent)
PYMARE_ENUM_CONVERSION(IREffect)
PYMARE_ENUM_CONVERSION(IRJumpKind)
PYMARE_ENUM_CONVERSION(IRConstTag)
PYMARE_ENUM_CONVERSION(IRType)
PYMARE_ENUM_CONVERSION(IROp)
PYMARE_ENUM_CONVERSION(IRLoadGOp)

void pyvex_init_enums()
{
	PYMARE_ENUM_INIT(VexArch)
	PYMARE_ENUM_INIT(IRExprTag)
	PYMARE_ENUM_INIT(IRStmtTag)
	PYMARE_ENUM_INIT(IREndness)
	PYMARE_ENUM_INIT(IRMBusEvent)
	PYMARE_ENUM_INIT(IREffect)
	PYMARE_ENUM_INIT(IRJumpKind)
	PYMARE_ENUM_INIT(IRConstTag)
	PYMARE_ENUM_INIT(IRType)
	PYMARE_ENUM_INIT(IROp)
	PYMARE_ENUM_INIT(IRLoadGOp)

	#include "generated_enums"
}
