name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ecosystem:
    uses: angr/ci-settings/.github/workflows/angr-ci.yml@master

  test:
    name: Test
    strategy:
      matrix:
        os: [windows-2022, macos-13, macos-15, ubuntu-24.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Activate msvc
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
        if: startsWith(runner.os, 'windows')
      - name: Setup uv
        uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6
      - name: Sync dependencies
        run: uv sync -p 3.10
      - name: Run tests
        run: uv run pytest tests

