name: Test on macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos:
    name: Test macOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: pyvex
          submodules: true
      - uses: actions/checkout@v3
        with:
          repository: angr/binaries
          path: binaries
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          source $HOME/venv/bin/activate
          pip install git+https://github.com/angr/archinfo.git
        name: Install dependencies
      - run: |
          source $HOME/venv/bin/activate
          pip install ./pyvex[testing]
        name: Install
      - run: |
          source $HOME/venv/bin/activate
          pytest -n auto pyvex
        name: Run pytest
