name: WebAssembly

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          submodules: recursive
      - name: Build and test Pyodide wheel
        uses: pypa/cibuildwheel@v4.1.0
        with:
          package-dir: .
        env:
          CIBW_PLATFORM: pyodide
      - name: Store Pyodide wheel
        uses: actions/upload-artifact@v7
        with:
          name: pyodide-wheel
          path: wheelhouse/*.whl

  publish:
    runs-on: ubuntu-24.04
    if: github.event_name == 'release'
    needs: [build]
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: pyodide-wheel
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
